apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        kind: HelmRepository
        name: keycloak
      version: "2.2.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: quay.io/keycloak/keycloak
      tag: latest
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: keycloak-reg-cred
    command:
    - /opt/keycloak/bin/kc.sh
    - --verbose
    - start
    - --http-enabled=true
    - --http-port=8080
    - --hostname-strict=false
    - --hostname-strict-https=false
    - --log-console-output=json
    - --spi-events-listener-jboss-logging-success-level=info
    - --spi-events-listener-jboss-logging-error-level=warn
    - --import-realm
    database:
      database: app
      existingSecret: keycloak-db-app
      existingSecretKey: password
      hostname: keycloak-db-rw
      port: 5432
      username: app
      vendor: postgres
    dbchecker:
      enabled: true
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-http
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-http
            key: password
      - name: JAVA_OPTS_APPEND
        value: >-
          -XX:+UseContainerSupport
          -XX:MaxRAMPercentage=50.0
          -Djava.awt.headless=true
          -Djgroups.dns.query=keycloak-headless
    fullnameOverride: keycloak
    ingress:
      enabled: true
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production-issuer
        nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      ingressClassName: nginx
      rules:
      - host: keycloak.${domain}
        paths:
        - backend:
            service:
              name: keycloak-http
              port:
                name: http
          path: /auth/
          pathType: Prefix
      tls:
      - hosts:
        - keycloak.${domain}
        secretName: keycloak-tls
    metrics:
      enabled: true
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1200Mi
      requests:
        cpu: 200m
        memory: 1200Mi
    service:
      extraPorts:
      - name: metrics-port
        port: 8080
        protocol: TCP
        targetPort: 8080
