apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - logging
  # - monitoring
  - metrics-server.yaml
  - postgres-operator
  - cert-manager.yaml
  - ingress-nginx.yaml
  - weave-gitops.yaml
  - rabbitmq-cluster-operator.yaml