---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      version: 5.15.0
  install:
    createNamespace: true
  interval: 24h0m0s
  targetNamespace: observability

  values:
    loki:
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
    tableManager:
      enabled: true
      retention_deletes_enabled: true
      extraVolumes:
        - name: data
          emptyDir: {}
      extraVolumeMounts:
        - name: data
          mountPath: /var/loki
    monitoring:
      # Dashboards for monitoring Loki
      dashboards:
        # -- If enabled, create configmap with dashboards for monitoring Loki
        enabled: true
