apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      version: 6.15.0
  install:
    createNamespace: true
  interval: 24h0m0s
  targetNamespace: observability

  values:
    config:
      logLevel: info
      serverPort: 3101
      lokiAddress: http://loki:3100/loki/api/v1/push
