# 
# Add permissions to the standard K8s roles to allow admin users to create Cloud native Postgres manifests such as postgresclusters
# 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["backups", "clusters","poolers", "scheduledbackups"]
    verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["backups", "clusters","poolers", "scheduledbackups"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]
---


