---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: middleware
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./middleware/staging
  prune: true
  wait: true
  timeout: 5m0s
  postBuild:
    substitute:
      domain: "test-dataplatform.online"